// <auto-generated>
//   Generated by Xantham.Generator from strip-ansi.
//   Do not edit by hand - regenerate instead.
// </auto-generated>
module rec StripAnsi

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Core.JS

/// <summary>The package's value exports, each bound to its import.</summary>
[<Erase>]
type Exports =
    /// <summary>
    /// Strip [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) from a string.
    /// </summary>
    /// <remarks>
    /// @example
    /// <code>
    /// import stripAnsi from 'strip-ansi';
    ///
    /// stripAnsi('\u001B[4mUnicorn\u001B[0m');
    /// //=&gt; 'Unicorn'
    ///
    /// stripAnsi('\u001B]8;;https://github.com\u0007Click\u001B]8;;\u0007');
    /// //=&gt; 'Click'
    /// </code>
    /// </remarks>
    [<Import("default", "strip-ansi")>]
    static member stripAnsi (string: string) : string = jsNative
