<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>netstandard2.1</TargetFramework><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><Compile Include="Program.fs" /><ProjectReference Include="../../src/BindingsProduct/BindingsProduct.fsproj" /><PackageReference Include="Fable.Core" /></ItemGroup></Project>
